log_dir: .
log_name: ayame.log
log_level: info
addr: localhost
port_plain: 3000
port_secure: 3443
max_sessions: 100
file_dir: asset
check_period: 10
send_timout: 10
recv_timeout: 10

# - Set flag for ping-pong in json format 
#over_ws_ping_pong: true

# - Authenticated Webhook URL
# auth_webhook_url: http://127.0.0.1:3001/auth/webhook

# - Set origin in websocket
# allow_origin: *.example.com
